// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuZpXgfY9s9pdvZAR-opf3rdFIRDYdjXc',
    appId: '1:747640958490:web:2d5ceaf5164520dfa5aba3',
    messagingSenderId: '747640958490',
    projectId: 'test-15979',
    authDomain: 'test-15979.firebaseapp.com',
    databaseURL: 'https://test-15979-default-rtdb.firebaseio.com',
    storageBucket: 'test-15979.appspot.com',
    measurementId: 'G-7DGNRVN89L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQ7oAmnF-vUyajFF4KiwKpUQWujzQkHU',
    appId: '1:747640958490:android:5b7deca9f0e318afa5aba3',
    messagingSenderId: '747640958490',
    projectId: 'test-15979',
    databaseURL: 'https://test-15979-default-rtdb.firebaseio.com',
    storageBucket: 'test-15979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0_inR58ldL0_P45PrI2jJg5_j7_wHHU0',
    appId: '1:747640958490:ios:8ed67eb4fb1cd166a5aba3',
    messagingSenderId: '747640958490',
    projectId: 'test-15979',
    databaseURL: 'https://test-15979-default-rtdb.firebaseio.com',
    storageBucket: 'test-15979.appspot.com',
    iosClientId: '747640958490-31ssf0pdcnp6n08bhln25l2ir2gg9e9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.signalReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0_inR58ldL0_P45PrI2jJg5_j7_wHHU0',
    appId: '1:747640958490:ios:fe878cbe2b2ac720a5aba3',
    messagingSenderId: '747640958490',
    projectId: 'test-15979',
    databaseURL: 'https://test-15979-default-rtdb.firebaseio.com',
    storageBucket: 'test-15979.appspot.com',
    iosClientId: '747640958490-4bku3ncvmpl69j34r126lv0bjm108at1.apps.googleusercontent.com',
    iosBundleId: 'com.example.signalReader.RunnerTests',
  );
}
